version: 1

build:
  type: node
  upload_artifacts: false
  path: web
  artifact_name: pianoter-web
  upload_artifact: false
  test_cmd: "make test-frontend"

release:
  rolling: false
  on-tag: true
